import type { Metadata } from "next";
import "./globals.css";
import { AppProvider } from "@/context/AppContext";
import { SocketProvider } from "@/context/SocketContext";
import { CallProvider } from "@/context/CallContext";
import CallOverlay from "@/components/CallOverlay";
import { ThemeProvider } from "@/context/ThemeContext";
import ThemeToggle from "@/components/ThemeToggle";

export const metadata: Metadata = {
  title: "Chat App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <ThemeProvider>
          <ThemeToggle />
          <AppProvider>
            <SocketProvider>
              <CallProvider>
                {children}
                <CallOverlay />
              </CallProvider>
            </SocketProvider>
          </AppProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
